grupotesseract/fibra-mobile

- src/screens/Login/Login.tsx
Na tela de login os inputs e botões acompanham a tela ao abrir o teclado
Closes #168650639
> feat(input-flex): Input e botão sempre aparecendo

- app.json
- package-lock.json
- package.json
- src/components/QRCodeReader.tsx
- src/screens/ManutencaoIluminacao/ManutencaoIluminacao.tsx
Adicionado componente de leitor de QRCode, porém nada faz com o código
gerado, apenas redireciona para uma tela interna de Item.
Closes #169045437
> feat(leitor-qrcode): Componente leitor do QRCode

- src/App.tsx
- src/screens/Colaboradores/Colaboradores.tsx
- src/screens/LiberarDocumento/index.tsx
- src/screens/ManutencaoIluminacao/ManutencaoItem.tsx
- src/screens/Menu/Menu.tsx
Dodo, a UX que eu pensei no select de Colaboradores na tela de Liberação de Documento pode ser polêmica, por isso nem vou descrevê-la pra que você tire suas próprias conclusões heheh
> 169364385 select colaboradores

- src/screens/Login/Login.tsx
- src/screens/SelecionaPlanta/SelecionarPlanta.tsx
- src/services/api.ts
- src/store/ducks/auth/sagas.ts
- src/store/ducks/empresas/sagas.ts
Requisição simples pegando empresas e plantas para preenchimento do select
> #168902808 Integração com o endpoint de Empresas e Plantas

- src/App.tsx
- src/screens/Menu/Menu.tsx
- src/screens/Programacoes/Programacoes.tsx
Foi o melhor que consegui fazer, a um passo de eu não tacar meu notebook pela janela
> 169813455 tela programacoes

- package-lock.json
- package.json
- src/App.tsx
- src/screens/Login/Login.tsx
- src/screens/Menu/Menu.tsx
- src/screens/SelecionaPlanta/SelecionarPlanta.tsx
- src/screens/SyncEmpresas/SyncEmpresas.tsx
- src/services/api.ts
- src/store/ducks/auth/actions.ts
- src/store/ducks/auth/index.ts
- src/store/ducks/auth/sagas.ts
- src/store/ducks/auth/types.ts
- src/store/ducks/empresas/index.ts
- src/store/ducks/empresas/sagas.ts
- src/store/index.ts
- src/utils/authNavigation.ts
Estrutura do redux-saga com suporte ao sync de empresas e plantas,
armazenamento do token e role do usuário
Closes #169502769
Closes #170009118
Closes #170005763
> feat(reduxsync) Sincronização: empresas e plantas 

- src/screens/Login/Login.tsx
- src/screens/Menu/Menu.tsx
- src/screens/SyncEmpresas/SyncEmpresas.tsx
- src/store/ducks/auth/sagas.ts
- src/store/ducks/empresas/sagas.ts
- src/store/ducks/rootReducer.ts
- src/store/ducks/rootSaga.ts
- src/store/ducks/usuarios/actions.ts
- src/store/ducks/usuarios/index.ts
- src/store/ducks/usuarios/types.ts
- src/store/index.ts
Usuários armazenados na local storage, permissão de login offline para
usuários que não são administradores.
Closes #170033085
> feat(authoffline) Sync e autorização offline

- src/screens/ConfirmarPeriodoManutencao/index.tsx
- src/screens/LiberarDocumento/index.tsx
- src/screens/SelecionaPlanta/SelecionarPlanta.tsx
- src/store/ducks/auth/index.ts
- src/store/ducks/auth/sagas.ts
- src/store/ducks/empresas/types.ts
- src/store/ducks/planta/actions.ts
- src/store/ducks/planta/index.ts
- src/store/ducks/planta/types.ts
- src/store/ducks/programacoes/actions.ts
- src/store/ducks/programacoes/index.ts
- src/store/ducks/programacoes/types.ts
- src/store/ducks/rootReducer.ts
- src/store/index.ts
Telas implementadas: Confirmar perído da manutenção, Liberação de
documentos
- Exibindo inicio e fim planejados da próxima programação
- Salva no banco local a data da confirmação
- Listagem de colaboradores que possuem a role 'tecnico'
- Salva data e hora da liberação de documentos
Closes #170114141
> feat(liberacao): Manutenção e liberação de docs

- src/screens/ComentariosGerais/ComentariosGerais.tsx
- src/screens/Estoque/Estoque.tsx
- src/screens/ManutencaoIluminacao/ManutencaoIluminacao.tsx
- src/screens/ManutencaoIluminacao/ManutencaoItem.tsx
- src/screens/SelecionaPlanta/SelecionarPlanta.tsx
- src/screens/SyncEmpresas/SyncEmpresas.tsx
- src/store/ducks/empresas/index.ts
- src/store/ducks/empresas/sagas.ts
- src/store/ducks/planta/index.ts
- src/store/ducks/planta/types.ts
- src/store/ducks/rootReducer.ts
- src/store/index.ts
Exibição de informações da manutenção de itens; bind do Redux em páginas
de Estoque, Materiais, e Manutenção;
Leitura do QRCode com verificação se o Item está presente na planta
atual;
Closes #170218062
Closes #170235229
> feat(manutencaoitens): Exibição de infos

- src/App.tsx
- src/screens/ComentariosGerais/ComentariosGerais.tsx
- src/screens/FotosItem/FotosItem.tsx
- src/screens/LiberarDocumento/index.tsx
- src/screens/ManutencaoIluminacao/ManutencaoIluminacao.tsx
- src/screens/ManutencaoIluminacao/ManutencaoItem.tsx
- src/screens/Programacoes/Programacoes.tsx
- src/screens/SelecionaPlanta/SelecionarPlanta.tsx
- src/services/api.ts
- src/store/ducks/empresas/sagas.ts
- src/store/ducks/planta/types.ts
- src/store/ducks/programacoes/actions.ts
- src/store/ducks/programacoes/index.ts
- src/store/ducks/programacoes/types.ts
- src/store/index.ts
- src/utils/authNavigation.ts
- yarn.lock
- Armazenando quantidades vistoriadas
- Armazenando lista com endereço físico das fotos
- Armazenando comentário de cada item
- Salvando estado de conclusão (e impedindo o usuário de editar a manutenção)
> Armazenando manutenção de itens

- src/screens/ComentariosGerais/ComentariosGerais.tsx
- src/screens/ManutencaoIluminacao/ManutencaoItem.tsx
- src/screens/MenuVistoria/MenuVistoria.tsx
- src/store/ducks/programacoes/actions.ts
- src/store/ducks/programacoes/index.ts
- src/store/ducks/programacoes/types.ts
Armazenando localmente comentários gerais e comentário de cada item;
Armazenando localmente o _datetime_ do momento em que o item é
visualizado e do momento em que ele é concluído
Closes #170265810
Closes #170282438
> feat(comentariosehorarios) Comentários e datas

- src/App.tsx
- src/screens/ConfirmarPeriodoManutencao/index.tsx
- src/screens/EntradaMateriais/EntradaMateriais.tsx
- src/screens/Estoque/Estoque.tsx
- src/screens/ManutencaoIluminacao/ManutencaoIluminacao.tsx
- src/screens/SelecionaPlanta/SelecionarPlanta.tsx
- src/services/api.ts
- src/store/ducks/planta/index.ts
- src/store/ducks/planta/types.ts
- src/store/ducks/programacoes/actions.ts
- src/store/ducks/programacoes/index.ts
- src/store/ducks/programacoes/types.ts
Exibindo materiais e armazenando localmente os dados de Estoque e Entrada
Closes #170327706
Closes #170327707
Closes #170218042
Closes #170005899
Closes #170282354
> feat(estoqueentrada): Estoque e Entrada

- src/screens/Colaboradores/Colaboradores.tsx
- src/screens/ConfirmarPeriodoManutencao/index.tsx
- src/screens/Login/Login.tsx
- src/screens/MenuVistoria/MenuVistoria.tsx
- src/screens/Programacoes/Programacoes.tsx
- src/services/api.ts
- src/utils/authNavigation.ts
- src/utils/utils.ts
- Melhoria nas informações de algumas telas
- tipagem de variaveis
- bugfix do token que não carregava
- Exibindo listagem de colaboradores armazenados no dispositivo
- Desabilitando estoque e entrada de materiais apos conclusão
Closes #170327678
Closes #170327674
> feat(melhorias): Melhorias gerais

- src/screens/EntradaMateriais/EntradaMateriais.tsx
- src/screens/ManutencaoIluminacao/ManutencaoIluminacao.tsx
- src/screens/Menu/Menu.tsx
- src/screens/MenuVistoria/MenuVistoria.tsx
- src/screens/Programacoes/Programacoes.tsx
- src/store/ducks/programacoes/actions.ts
- src/store/ducks/programacoes/index.ts
- src/store/ducks/programacoes/types.ts
- Escondendo btn de programação
- Data fim manutenção
Closes #170348883
Closes #170326912
Closes #170346086
> feat(diversos): Diversos ajustes

- src/screens/LiberarDocumento/index.tsx
- src/screens/ManutencaoIluminacao/ManutencaoIluminacao.tsx
- src/screens/ManutencaoIluminacao/ManutencaoItem.tsx
- src/screens/Menu/Menu.tsx
- src/screens/MenuVistoria/MenuVistoria.tsx
- src/screens/SyncEmpresas/SyncEmpresas.tsx
Estudo de problemas de performance; 
bugfix ao marcar data_inicio pelo qrcode
>  bugfix ao marcar data_inicio pelo qrcode

- src/screens/ComentariosGerais/ComentariosGerais.tsx
- src/screens/ManutencaoIluminacao/ManutencaoIluminacao.tsx
Carregando comentários e quantidades armazenadas localmente
Closes #170323697
Closes #170323712
> feat(comentarios): Comentários e quantidades

- src/screens/ComentariosGerais/ComentariosGerais.tsx
- src/screens/FotosItem/FotosItem.tsx
- src/screens/ManutencaoIluminacao/ManutencaoIluminacao.tsx
- src/screens/ManutencaoIluminacao/ManutencaoItem.tsx
- src/services/api.ts
- src/store/ducks/programacoes/index.ts
Tentei fazer do jeito que você me ensinou, mas mesmo assim nao rolou. tem que testar o objeto inteiro mesmo.
> Verificando existencia de Comentarios

- src/screens/ConfirmarPeriodoManutencao/index.tsx
- src/screens/LiberarDocumento/index.tsx
- src/screens/ManutencaoIluminacao/ManutencaoItem.tsx
- src/store/ducks/programacao/index.ts
Substituindo o objeto Date por uma string no formato ISO
> fix(datas): Datas em formato ISO

- src/store/ducks/programacoes/index.ts
Correção do erro de Comentários de um Item, que estavam sendo sobrescritos quando o usuário fizesse uma alteração em outro item
Closes #171116838
> fix(comentarioitem): Correção comentário item

- src/screens/ManutencaoIluminacao/ManutencaoItem.tsx
- src/screens/Programacoes/Programacoes.tsx
- src/screens/SelecionaPlanta/SelecionarPlanta.tsx
- src/services/api.ts
- src/store/ducks/programacao/index.ts
- src/store/ducks/programacao/types.ts
- src/store/ducks/programacoes/actions.ts
- src/store/ducks/programacoes/index.ts
- src/store/ducks/programacoes/types.ts
- yarn.lock
Correçãos dos erros referentes à sincronização de programações e seleção de empresas;
Implementação de funcionalidade que bloqueia botão de concluir
manutenção de um item e só libera depois que pelo menos uma foto foi
tirada
Closes #171111909
Closes #171028622
Closes #171111791
> feat(manutencao) Concluir e sincronizar manutenção

- app.json
- src/screens/Programacoes/Programacoes.tsx
Melhorias no envio de dados e fotos, assim como no tratamento dos erros
> fix(sync): Sincronização com tratamento de envio

- src/screens/Programacoes/Programacoes.tsx
- src/services/api.ts
Correção do erro ao sincronizar
Finish #171729202
> fix(uploadfotos): Erro de split no upload

- src/App.tsx
- src/screens/Cliente/Comentarios/Comentarios.tsx
- src/screens/Cliente/ManutencaoCliente/ManutencaoCliente.tsx
- src/screens/Cliente/Menu/Menu.tsx
- src/screens/ManutencaoEletrica/Comentarios/Comentarios.tsx
- src/screens/ManutencaoEletrica/FotosManutencaoEletrica/FotosManutencaoEletrica.tsx
- src/screens/ManutencaoEletrica/LiberarDocumento/index.tsx
- src/screens/ManutencaoEletrica/MenuManutencaoEletrica/MenuManutencaoEletrica.tsx
- src/screens/ManutencaoEletrica/SelecionaPlanta/SelecionarPlanta.tsx
- src/screens/Menu/Menu.tsx
- src/store/ducks/eletricaoucivil/actions.ts
- src/store/ducks/eletricaoucivil/index.ts
- src/store/ducks/eletricaoucivil/types.ts
Telas de Selecionar Planta, Liberar Documento e Menu interno da
menutenção Elétrica.
Telas de fotos e comentários internos da manutenção elétrica ou civil.
Menu interno para Manutenção de Cliente.
> Telas do front para manutenção elétrica ou civil e manutenção de cliente

- src/App.tsx
- src/screens/Menu/Menu.tsx
- src/screens/RDO/Comentarios/Comentarios.tsx
- src/screens/RDO/FotosRDO/FotosRDO.tsx
- src/screens/RDO/LiberarDocumento/EquipeLiberacao.tsx
- src/screens/RDO/LiberarDocumento/RegistroLiberacao.tsx
- src/screens/RDO/MenuRDO/MenuRDO.tsx
- src/screens/RDO/SelecionaPlanta/SelecionarPlanta.tsx
Modificação e Inclusão de Campos Texto nas telas internas do RDO
Closes #172186260
> feat(campostexto): Modificação e inclusao textos

- src/App.tsx
- src/screens/Menu/Menu.tsx
- src/screens/RDO/Comentarios/Comentarios.tsx
- src/screens/RDO/LiberarDocumento/EquipeLiberacao.tsx
- src/screens/RDO/LiberarDocumento/RegistroLiberacao.tsx
- src/screens/RDO/MenuRDO/MenuPrincipalRDO.tsx
- src/screens/RDO/MenuRDO/MenuRDO.tsx
- src/screens/RDO/SelecionaPlanta/SelecionarPlanta.tsx
- src/screens/RDO/Sincronizacao/Sincronizacao.tsx
- src/store/ducks/auth/sagas.ts
- src/store/ducks/rdo/actions.ts
- src/store/ducks/rdo/index.ts
- src/store/ducks/rdo/types.ts
Registro de horas nas seguintes etapas do RDO:
- Entrada
- Saida
- Inicio Atividades
- Inicio LEM
- Inicio LET
- Fim LEM
- Fim LET
Closes #172440381
> feat(rdo): Registro de Horas

- src/screens/RDO/FotosRDO/FotosRDO.tsx
- src/screens/RDO/MenuRDO/MenuRDO.tsx
- src/store/ducks/rdo/actions.ts
- src/store/ducks/rdo/index.ts
Salvando fotos na árvore do redux
Closes #172201206
> feat(rdo) Salvando Fotos

- src/screens/Menu/Menu.tsx
- src/screens/RDO/MenuRDO/MenuPrincipalRDO.tsx
- src/screens/RDO/MenuRDO/MenuRDO.tsx
- src/screens/RDO/Sincronizacao/Sincronizacao.tsx
- src/screens/SelecionaPlanta/SelecionarPlanta.tsx
- src/services/api.ts
- src/store/ducks/rdo/actions.ts
- src/store/ducks/rdo/index.ts
- src/store/ducks/rdo/types.ts
Sincronização e upload de fotos para os RDOs
Closes #172293425
> feat(rdo) Sincronização de RDOs

- src/screens/RDO/Sincronizacao/Sincronizacao.tsx
- src/services/api.ts
- src/store/ducks/rdo/index.ts
- src/store/ducks/rdo/types.ts
Ícone de carregamento ao sincronizar dados e fotos
Closes 172744694
> feat(rdo): Loader no sync

- src/screens/RDO/FotosRDO/FotosRDO.tsx
Correção de erro ao registrar as fotos do RDO
Closes #172795559
> fix(rdo) Fotos não persisitiam

- src/screens/Menu/Menu.tsx
Sincronização para atualizar empresas e usuários disponível para técnicos
Closes #172795464
> feat(sync) Liberar sync para técnicos

- src/App.tsx
- src/components/HeaderNav.tsx
- src/screens/ManutencaoIluminacao/IncluirMaterialAoItem.tsx
- src/screens/ManutencaoIluminacao/TodosMateriaisItem.tsx
- src/screens/Programacoes/Programacoes.tsx
- src/screens/SelecionaPlanta/SelecionarPlanta.tsx
- src/services/api.ts
- src/store/ducks/planta/actions.ts
- src/store/ducks/planta/index.ts
- src/store/ducks/planta/types.ts
- src/store/ducks/programacoes/actions.ts
- src/store/ducks/programacoes/index.ts
- src/store/ducks/programacoes/types.ts
Listagem de materiais com botão de edição de quantidade instalada;
Adicionando material ao item;
Enviando materiais na programação como itensAlterados
> Alteração de materiais do item

- src/App.tsx
- src/screens/ManutencaoIluminacao/IncluirMaterialAoItem.tsx
- src/screens/RDO/AtividadesPendentes/AtividadesPendentes.tsx
- src/screens/RDO/LiberarDocumento/RegistroLiberacao.tsx
- src/services/api.ts
- src/store/ducks/planta/types.ts
@evandrododo eu tenho CERTEZA ABSOLUTA que o jeito que eu to filtrando as plantas e as empresas está errado, mas foi a única maneira que consegui fazer funcionar. Me perdi um pouco pelo fato do RDO não ter uma plantaAtiva, e sim apenas o id da planta ativa, aí não consegui filtrar o objeto de empresas de uma maneira inteligente. Acredito que seja uma falta de conhecimentos de JS nesse caso. Peço encarecidamente que dê seu pitaco e caso tenha uma solução melhor, nos ajude kkkkkk
> 172795461 tela atividadesrealizadas

- src/screens/ManutencaoIluminacao/ManutencaoItem.tsx
- src/screens/ManutencaoIluminacao/TodosMateriaisItem.tsx
- src/screens/RDO/AtividadesPendentes/AtividadesPendentes.tsx
- src/store/ducks/programacoes/index.ts
- src/store/ducks/programacoes/types.ts
Persistindo quantidade isntalada dos materiais alterados dentro do item, assim como o status do botão de concluído de cada material
> fix(persist) Persistindo materiais alterados

- package.json
- src/screens/Login/Login.tsx
- src/screens/RDO/Sincronizacao/Sincronizacao.tsx
- src/services/api.ts
- src/store/ducks/auth/sagas.ts
- yarn.lock
Correção dos RDOs sem id, inserido teste de conectividade no login
[finishes #173366045]
[finishes #173368308]
> fix(auth) Teste de conectividade e fix rdo

- app.json
https://docs.expo.io/guides/offline-support/
> Ajuste no app.json para build dos assets, em vez de usar os CDNs do Expo

- src/screens/ManutencaoIluminacao/IncluirMaterialAoItem.tsx
- src/screens/ManutencaoIluminacao/ManutencaoItem.tsx
- src/screens/ManutencaoIluminacao/TodosMateriaisItem.tsx
Botão para cancelar inclusão de um item
[finishes #173300424]
> feat(editar-material) Cancelar inclusão

- package-lock.json
- src/screens/Login/Login.tsx
- src/screens/ManutencaoIluminacao/IncluirMaterialAoItem.tsx
- src/screens/ManutencaoIluminacao/TodosMateriaisItem.tsx
- src/services/api.ts
- src/store/ducks/planta/types.ts
- src/store/ducks/programacoes/index.ts
Basicamente, incluí dois novos campos para Base e Reator, na tela de alteração dos itens. Esses campos são exibidos apenas no caso de novos materiais incluídos.
> 173878741 suporte base alteracao
